# LambdaTest Configuration

# Project and folder configuration
project_id: "01KK7YVSSKHWSZV7HEDR6QNFMK"
folder_id: "01KK7YW6TQXDHDV7XVB4AC3MWY"

# Test Run configuration
assignee: 26052
environment_id: 223776

# Test URL for automation
# test_url: "https://demo.lambdatestinternal.com"
